
import React, { useState } from 'react';
import { Button } from "@/components/ui/button";
import { Plus, Eye, Edit, Search } from "lucide-react";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { WOFilterDialog } from "@/components/WOFilterDialog";
import { useNavigate } from 'react-router-dom';

export const WODashboard = () => {
  const navigate = useNavigate();
  const [searchQuery, setSearchQuery] = useState('');
  const [isFilterDialogOpen, setIsFilterDialogOpen] = useState(false);

  const woData = [
    {
      id: 1175,
      action: "Edit",
      woNo: "NA",
      referenceNo: "100/05/2025",
      createdBy: "MORDEN LIFESCIENCES PVT LTD",
      createdOn: "Pending",
      supplier: "",
      approvalStatus: "Pending",
      paymentTenureInDays: "10000.00",
      woAmount: "0.0",
      totalAmtCritNAmount: "0.0",
      generatedBy: "0.0",
      retentionPercent: "0.0",
      retentionOutstanding: "0.0",
      qcAmount: "0.0",
      noOfItems: "10000.00",
      totalAmountPaid: "No",
      outstanding: "Sun Engineering",
      debtCollectionNoteRaised: "19/05/2025",
      createdBy2: "",
      uploadedBy: "",
      updatedOn: ""
    }
  ];

  const getStatusColor = (status: string) => {
    switch (status.toLowerCase()) {
      case 'approved':
        return 'bg-green-500 text-white';
      case 'rejected':
        return 'bg-red-500 text-white';
      case 'pending':
        return 'bg-yellow-500 text-black';
      default:
        return 'bg-gray-500 text-white';
    }
  };

  const filteredData = woData.filter(item =>
    item.referenceNo.toLowerCase().includes(searchQuery.toLowerCase()) ||
    item.createdBy.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <div className="p-6">
      {/* Breadcrumb */}
      <div className="mb-4 text-sm text-gray-600">
        WO
      </div>

      {/* Page Title */}
      <h1 className="text-2xl font-bold mb-6">WORK ORDER LIST</h1>

      {/* Action Buttons */}
      <div className="flex items-center justify-between mb-6">
        <div className="flex gap-3">
          <Button 
            style={{ backgroundColor: '#F2EEE9', color: '#BF213E' }}
            className="hover:bg-[#F2EEE9]/90"
            onClick={() => navigate('/finance/wo/add')}
          >
            <Plus className="w-4 h-4 mr-2" />
            Add
          </Button>
          <Button 
            variant="outline"
            onClick={() => setIsFilterDialogOpen(true)}
          >
            Filters
          </Button>
        </div>

        <div className="flex items-center gap-3">
          <div className="relative">
            <Search className="w-4 h-4 absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" />
            <input
              type="text"
              placeholder="Search"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#BF213E] focus:border-transparent w-64"
            />
          </div>
          <Button 
            style={{ backgroundColor: '#F2EEE9', color: '#BF213E' }}
            className="hover:bg-[#F2EEE9]/90 px-4"
          >
            Go!
          </Button>
          <Button 
            variant="outline" 
            className="px-4"
            onClick={() => setSearchQuery('')}
          >
            Reset
          </Button>
        </div>
      </div>

      {/* Table */}
      <div className="bg-white rounded-lg shadow overflow-x-auto">
        <Table>
          <TableHeader>
            <TableRow className="bg-gray-50">
              <TableHead className="font-semibold">Action</TableHead>
              <TableHead className="font-semibold">ID</TableHead>
              <TableHead className="font-semibold">WO No.</TableHead>
              <TableHead className="font-semibold">Reference No.</TableHead>
              <TableHead className="font-semibold">Created by</TableHead>
              <TableHead className="font-semibold">Supplier</TableHead>
              <TableHead className="font-semibold">Approval Status</TableHead>
              <TableHead className="font-semibold">Payment Tenure (in Days)</TableHead>
              <TableHead className="font-semibold">Advance Amount</TableHead>
              <TableHead className="font-semibold">Total Amount</TableHead>
              <TableHead className="font-semibold">WO Amount</TableHead>
              <TableHead className="font-semibold">Total Amt Crit N Amount</TableHead>
              <TableHead className="font-semibold">Generated By</TableHead>
              <TableHead className="font-semibold">Retention (%)</TableHead>
              <TableHead className="font-semibold">Retention Outstanding</TableHead>
              <TableHead className="font-semibold">QC Amount</TableHead>
              <TableHead className="font-semibold">No of Items</TableHead>
              <TableHead className="font-semibold">Total Amount Paid</TableHead>
              <TableHead className="font-semibold">Outstanding</TableHead>
              <TableHead className="font-semibold">Debt Collection Note Raised</TableHead>
              <TableHead className="font-semibold">Created by</TableHead>
              <TableHead className="font-semibold">Uploaded by</TableHead>
              <TableHead className="font-semibold">Updated On</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {filteredData.map((item) => (
              <TableRow key={item.id}>
                <TableCell>
                  <Button size="sm" variant="ghost" className="p-1">
                    <Edit className="w-4 h-4" />
                  </Button>
                </TableCell>
                <TableCell className="font-medium">{item.id}</TableCell>
                <TableCell>{item.woNo}</TableCell>
                <TableCell className="text-blue-600 hover:underline cursor-pointer">
                  {item.referenceNo}
                </TableCell>
                <TableCell>{item.createdBy}</TableCell>
                <TableCell>{item.supplier}</TableCell>
                <TableCell>
                  <span className={`px-2 py-1 rounded text-xs font-medium ${getStatusColor(item.approvalStatus)}`}>
                    {item.approvalStatus}
                  </span>
                </TableCell>
                <TableCell>{item.paymentTenureInDays}</TableCell>
                <TableCell className="font-medium">{item.woAmount}</TableCell>
                <TableCell>{item.totalAmtCritNAmount}</TableCell>
                <TableCell>{item.woAmount}</TableCell>
                <TableCell>{item.totalAmtCritNAmount}</TableCell>
                <TableCell>{item.generatedBy}</TableCell>
                <TableCell>{item.retentionPercent}</TableCell>
                <TableCell>{item.retentionOutstanding}</TableCell>
                <TableCell>{item.qcAmount}</TableCell>
                <TableCell>{item.noOfItems}</TableCell>
                <TableCell>{item.totalAmountPaid}</TableCell>
                <TableCell>{item.outstanding}</TableCell>
                <TableCell>{item.debtCollectionNoteRaised}</TableCell>
                <TableCell>{item.createdBy2}</TableCell>
                <TableCell>{item.uploadedBy}</TableCell>
                <TableCell>{item.updatedOn}</TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>

      <WOFilterDialog 
        open={isFilterDialogOpen}
        onOpenChange={setIsFilterDialogOpen}
      />
    </div>
  );
};
